title = "PlannedReview Configuration File"

[llm]

[llm.chat]
local = true
provider = "google" # openai, copilot, google ; assumed openai compatable if local = true
model = "muse"
api_key = "fake" # provide key here or in environment variable
address = "http://192.168.0.50:8080/v1" # only required if local = true

[llm.embed]
local = true
provider = "google" # openai, copilot, google
model = "gemma-embedding"
api_key = "fake" # provide key here or in environment variable
address = "http://192.168.0.50:8080/v1" # openai, copilot, google ; assumed openai compatable if local = true

[utils]
split_pdf = false
copy_pdf = false